version: '3.3'
#dev
services:

  tomcat:
   image: ${IMAGE}:${TAG}
   container_name: seqdb_public
   environment:
    - VIRTUAL_HOST=seqpublic.nrm.se
    #- VIRTUAL_HOST=public.nrm.se
    #- VIRTUAL_PORT=8080
   ports:
    - 8080:8080
   external_links: 
    - db:db
   extra_hosts:
    - "db:127.0.0.1"
   volumes:
    - ./srv/logs:/opt/tomcat/logs

networks:
  default:
    external:
       name: proxy-docker_default

