version: '3.1'

services:

  tomcat:
   image: dina/seqdb_ui:v3.17
   container_name: seqdb_public
   environment:
    - VIRTUAL_HOST=public_seqdb.dina-web.net
    - VIRTUAL_PORT=8080
   external_links: 
    - db:db
   extra_hosts:
    - "lenovo:172.16.23.33"
    - "db:172.16.23.33"
   volumes:
    - ./srv/logs:/opt/tomcat/logs

networks:
  default:
    external:
       name: proxydocker_default

