version: '3.1'

services:

  tomcat:
   image: dina/seqdb_ui:v3.17
   container_name: seqdb_public
   environment:
   #- VIRTUAL_HOST=cgi.dina-web.net
    - VIRTUAL_HOST=seqpublic.nrm.se
    - VIRTUAL_PORT=8080
   external_links: 
    - db:db
   extra_hosts:
    - "db:193.10.57.76"
   volumes:
    - ./srv/logs:/opt/tomcat/logs

networks:
  default:
    external:
       name: proxydocker_default

