fs.db:
  image: tianon/true
  volumes:
    - ./mysql_datadir:/var/lib/mysql
    - ./mysql_autoload:/docker-entrypoint-initdb.d:ro

fs.tomcat:
  image: tianon/true
  volumes:
    - ./srv/logs:/opt/tomcat/logs

db:
  image: mysql:5.6
  container_name: seqdb_public_db
  env_file: .env
  volumes_from:
    - fs.db

seqdb-public:
  image: dina/seqdb_ui:v3.15
  container_name: seqdb_public
   #ports:
   # - "18080:8080" # http://localhost:18080
  environment:
    - VIRTUAL_HOST=public.nrm.se
    - VIRTUAL_PORT=8080
  links:
    - db:db
  volumes_from:
    - fs.tomcat
