version: '3.3'

services:

  tomcat:
   image: ${IMAGE}
   container_name: seqdb_public
   environment:
    - VIRTUAL_HOST=seqpublic.nrm.se
    - VIRTUAL_PORT=8080
   external_links: 
    - db:db
   extra_hosts:
    - "db:192.168.1.238" #local-machine
   volumes:
    - ./srv/logs:/opt/tomcat/logs

networks:
  default:
    external:
       name: proxy-docker_default

