version: '3.3'

services:
  public-ui:
   image: ${IMAGE}
   container_name: seqpublic
   environment:
      #- VIRTUAL_HOST=seqpublic.nrm.se
      VIRTUAL_HOST: seqpublic.nrm.se
      spring.datasource.url: jdbc:postgresql://database/seqdb_prod?currentSchema=seqdb
      spring.datasource.username: seqdb_webapp
      spring.datasource.password: changeme
      spring.liquibase.enabled: "false" 
   external_links: 
    - database:database
   extra_hosts:
    - "database:193.10.57.76"
    # - "db:0.0.0.0"
    #volumes:
    #- ./srv/logs:/opt/tomcat/logs
networks:
  default:
    external:
      name: proxydocker_default

