version: '3.3'

services:

  seqpublic:
   image: ${IMAGE}
   container_name: seqdb_public
   environment:
    - VIRTUAL_HOST=seqpublic.nrm.se
   external_links: 
    - db:db
   extra_hosts:
    - "db:0.0.0.0"
   volumes:
    - ./srv/logs:/opt/tomcat/logs
networks:
  default:
    external:
       name: proxy-docker_default

