version: '3.1'

services:

  db:
    image: mysql:5.6
    container_name: seqdb_public_db
    env_file: .env
    volumes:
     - ./mysql_autoload:/docker-entrypoint-initdb.d:ro
     - ./mysql_datadir:/var/lib/mysql

networks:
  default:
    external:
       name: proxydocker_default
